credentials:
  usernames:
    felipe:
      email: felipe@email.com
      name: Felipe Amorim
      password: $2b$12$eIXRtz2Y3SPp3iGzZJzV9eC6rE70i8vVKbgnnk/f4a3uXnMZK9oeK  # senha: 123456

cookie:
  name: dashboard_cookie
  key: segredo_aleatorio123  # troque isso em produção
  expiry_days: 8

preauthorized:
  emails:
    - felipe@email.com
